### ISSUE TITLE
Install from custom iso?

### ISSUE THREAD

**Issue by leonardas103** [reynhout/chrx#10]
Would it be possible install from any iso? So instead of -d [distro] use some -o /path/to/iso ?
Would be nice if you can use chrx to install RemixOS.

**Comment by reynhout** [comment]
If you have an ISO, can't you simply boot from it?

Chrx is an installer -- but ISOs have their own installers to install their own payloads according to the rules set up in their installer program. Unfortunately, there's no way for chrx to know what any specific ISO's installer would do with the ISO content.

**Comment by leonardas103** [comment]
Ok then, would this work to install Remix OS alongside a chrx installed OS:
[http://forum.xda-developers.com/remix/remix-os/remix-os-installation-rooting-t3293769](url)

Does chrx a installed OS use grub?

**Comment by reynhout** [comment]
I don't know whether those instructions will work, but yes: chrx does install GRUB as a boot manager.
