### ISSUE TITLE
Installing to external media fails with mkfs error

### ISSUE THREAD

**Issue by reynhout** [reynhout/chrx#12]
Partitions are created properly, but the device files to access them do not exist, and are not created. When `mkfs` tries to format the partitions, it fails.

This appears to be due to a recent change in the ChromeOS environment.

I need to learn more about `udev` to fix this properly. It might be just a rule change (though I couldn't find an obvious blocker), or there might be a simple manual step (though the usual ones don't work).

**Comment by localredhead** [comment]
I ran into this yesterday I think - trying to install to an SD card

**Comment by localredhead** [comment]
I actually still get an error trying to install to an SD card.

**Comment by reynhout** [comment]
Can you post a log or screenshot?

**Comment by localredhead** [comment]
I tried to reproduce it again to obtain a screen shot, this time I had slightly different steps, but ended up with a successful install!

What was different this time:

- I logged into ChromeOS and mounted the drive first.  Then I initiated the install
- The install complained and failed, so I unmounted the drive per the command output
- Ran the install again and it worked!

Previously I did not have this, but rather got a mkfs error (which was different after I pulled these updates).  I guess I just had to keep trying :frowning: 

Sorry to raise alarm.  I'm going to do clean install of everything tonight and if I have issues again I'll try to gather more information.  I hope cell phone pictures of my screen will suffice - I'm not sure the best way to share the error output.

**Comment by reynhout** [comment]
OK, thanks for the update. You definitely do *not* want the media mounted by ChromeOS, but I realize that isn't documented.

If you're able to repro the error on a fresh boot, please do post screenshots. Logs are written to `/var/tmp/chrx/chrx-install.log` (in the ChromeOS partition) while installing, and copied to `/var/cache/chrx/chrx-install.log` (in the Linux partition) at the end.
