### ISSUE TITLE
[Question] Is it safe to do a release upgrade (from 15.10 to 16.04)?

### ISSUE THREAD

**Issue by CoolOppo** [reynhout/chrx#14]

**Comment by reynhout** [comment]
It should be. There's nothing special about a chrx-installed Ubuntu/etc except some configuration that isn't likely to be overwritten in an upgrade.

That said, I haven't tried it. So make sure you have backups. :)

If you're running GalliumOS (and you should be!) on the other hand -- no, don't do a release upgrade. You should not be prompted, and if you attempt it, it should not succeed...but just in case.
