### ISSUE TITLE
v2.2.4 installer tries to download Ubuntu "core" image instead of "base" one

### ISSUE THREAD

**Issue by codewrong** [reynhout/chrx#17]
Hello!

I see that you merged a patch for this in https://github.com/reynhout/chrx/commit/cb761648e2535a4c7dc77eb154e7f8020ae1996a but nevertheless when I `curl -Os https://chrx.org/sh && sh go` and try to download any *ubuntu based image, the installer tries to download the core image and exits.

Is there anything else I need to do to have those changes applied?

FWIW the installer says it is on v2.2.4.

Thanks

**Comment by reynhout** [comment]
Oops, quite right. Should be fixed now.

**Comment by codewrong** [comment]
Thanks. Keep up the good work :+1:

**Comment by reynhout** [comment]
Thanks for the update, and glad it worked!

**Comment by codewrong** [comment]
Sorry to be back, but now the installer does absolutely nothing 😢
