### ISSUE TITLE
Braswell support

### ISSUE THREAD

**Issue by fubarius** [reynhout/chrx#18]
What is needed for chrx to support the Braswell (successor to BayTrail) architecture used by the Intel Celeron 2560 in the new Acer Chromebook 14 (CB3-431)? I have one and would be willing to help out where I can. I'm assuming it would need a firmware update or something...

**Comment by reynhout** [comment]
Correct, you will need a firmware update to boot Linux. John Lewis has released firmware for a couple of Braswells, but not for the new Acer: https://johnlewis.ie/custom-chromebook-firmware/rom-download/

To my knowledge, he is the only one working on custom firmware for Braswell models at this time.

After that, you'll need an OS that has drivers/config for the hardware in that model, and no one knows yet what that will entail. Possibly nothing, but possibly more.

GalliumOS is the only OS of which I am aware that exclusively targets Chromebooks (/boxes), but if the modifications are minimal or the unsupported feature list is small, other OSes might work. Regardless, the GalliumOS community will generally be the first (or a very close second) to know about the status as it develops.
