### ISSUE TITLE
Automount is broken on GalliumOS

### ISSUE THREAD

**Issue by gmykhailiuta** [reynhout/chrx#19]
I've found auto-mount to be not working on Acer CB3-111 (GNAWTY) with dualboot (ChromeOS + GalliumOS 2 nightly).
This is caused by /etc/udev/rules.d/99-hide-disks.rules which makes system to ignore sda1-12, and that is the name which gets inserted flash drive, as soon as root (eMMC) device starts with mmcblk0*. I guess, that should affect all eMMC-backed chromebooks, but not sure.

**Comment by reynhout** [comment]
@gmykhailiuta Thanks for the report. You're right, that `udev` file is only appropriate for machines with an internal SSD at `/dev/sda`, so chrx needs to choose the config file based on hardware detection. Sorry for the difficulty!

**Comment by gmykhailiuta** [comment]
No problem! I appreciate your work. It would be great to contribute =)

**Comment by reynhout** [comment]
Should be fixed. Thanks again! :)
