### ISSUE TITLE
chromebook pixel 2013 link kubuntu 14.04

### ISSUE THREAD

**Issue by alvesadrian** [reynhout/chrx#21]
latest kernel upgrade crashed grub and also a fresh install of chrx is not working any more becasue grub update is failing cause the same as the kernel upgrade from an installed system

**Comment by reynhout** [comment]
Is this a problem with Kubuntu, or chrx?

**Comment by alvesadrian** [comment]
chronos@localhost ~ $ curl -Os https://chrx.org/go && sh go -d kubuntu -e desktop -r 14.04 -H PiXeL -U adrian -p admin-misc 
chrx installer, version 2.2.6

    Hardware ID: LINK_WISTERIA_BGY-K_7822
    Model:       Google Chromebook Pixel
    Released:    2013
    CPU Family:  Intel Ivy Bridge
    Prognosis:   success likely, per field reports

Checking hardware support for legacy boot...  OK
Setting up target disk /dev/sda...

Installing to /dev/sda7...
The file /dev/sda7 does not exist and no size was specified.
fatal: return code 1 from command "mkfs.ext4 -q /dev/sda7"
chronos@localhost ~ $

**Comment by alvesadrian** [comment]
am trying to reinstall it

**Comment by alvesadrian** [comment]
the grub problem happens in both chrx and kubuntu

**Comment by reynhout** [comment]
It looks like your partitions are damaged. You might need to recover to ChromeOS first, and then re-run chrx to set up partitions properly.

Are you getting an error message from GRUB?

**Comment by alvesadrian** [comment]
am about that but i cannot get the error now becasue the partition is corrupted, my main concern now is if i reinstall again kubuntu14.04 it wont fail again becasue of the latest kernel update 3.13

**Comment by alvesadrian** [comment]
also thanks for your fast answering reynhout i'll let you know what happens after recovery and start all over again

**Comment by reynhout** [comment]
It's a possibility. If you can upgrade to a newer version of Kubuntu, that might help. Chrx just installs whatever the distro publishes, unfortunately it isn't set up to fix distro-internal problems.

**Comment by alvesadrian** [comment]
@reynhout thanks for all your help, reinstall works fine. One question where this kernel is coming from?
adrian@PiXeL:~$ dpkg -l|grep linux-image
ii  linux-image-3.13.0-93-generic         3.13.0-93.140                           amd64        Linux kernel image for version 3.13.0 on 64 bit x86 SMP
ii  linux-image-3.17.1-031701-generic     3.17.1-031701.201410150735              amd64        Linux kernel image for version 3.17.1 on 64 bit x86 SMP
ii  linux-image-extra-3.13.0-93-generic   3.13.0-93.140                           amd64        Linux kernel extra modules for version 3.13.0 on 64 bit x86 SMP
ii  linux-image-generic                   3.13.0.93.100                           amd64        Generic Linux kernel image
adrian@PiXeL:~$ apt-cache policy linux-image-3.17.1-031701-generic
linux-image-3.17.1-031701-generic:
  Installed: 3.17.1-031701.201410150735
  Candidate: 3.17.1-031701.201410150735
  Version table:
 *** 3.17.1-031701.201410150735 0
        100 /var/lib/dpkg/status
adrian@PiXeL:~$ uname -a
Linux PiXeL 3.17.1-031701-generic #201410150735 SMP Wed Oct 15 11:36:31 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux


It looks like a custom kernel not from ubuntu, also my usb devices are not working i cannot mount devices like pendrives

**Comment by reynhout** [comment]
What version of what distro did you install?

3.17 is the minimum kernel version for several models. If your distro installs an older one, chrx will install 3.17 for you. It probably isn't adequate for a Pixel though.

You won't get full support for a Pixel from an old distro. Actually you won't get full support for a Pixel from any distro except GalliumOS (and currently only on the testing APT repo).

**Comment by alvesadrian** [comment]
am using kubuntu 14.04 from ChrX

**Comment by reynhout** [comment]
I wouldn't expect that to work well on a Pixel, even the 2013 model.
