### ISSUE TITLE
Steam doesn't install

### ISSUE THREAD

**Issue by Firminator** [reynhout/chrx#28]
reason:  chrx is trying to download from http://repo.steampowered.com/steam/archive/precise/steam_latest.deb which doesn't exist
updated link to latest files: http://repo.steamstatic.com/steam/pool/steam/s/steam/steam-launcher_1.0.0.54_all.deb

**Comment by Firminator** [comment]
Note: the GalliumOS Wiki for installing Steam ( https://wiki.galliumos.org/Additional_Software#Steam ) points to the outdated link as well.

**Comment by reynhout** [comment]
@Firminator Thanks for the report.

It looks like Valve has broken some links on their site.

* http://store.steampowered.com/ has a "Download Steam" link to:
* http://store.steampowered.com/about/ , which has a "Linux" download link to:
* https://steamcdn-a.akamaihd.net/client/installer/steam.deb , which redirects to:
* http://repo.steampowered.com/steam/archive/precise/steam_latest.deb

...which fails with 403 Forbidden.

I'd prefer not to specify a versioned package in chrx or the GalliumOS wiki, so I'll give Valve some time to fix things on their side.

**Comment by reynhout** [comment]
Literally while I was writing the above comment, Valve seems to have fixed it. :)

**Comment by Firminator** [comment]
Nice. Thanks for checking.
