### ISSUE TITLE
KVM disabled by BIOS?

### ISSUE THREAD

**Issue by taylorsangrey** [reynhout/chrx#29]
I am extremely confused. I have followed the install notes many times, tried many distros, etc and cannot get past this wall even with many hours of googling.

Moral of the story; Everything installs and boots fine, but GalliumOS gets past the boot screen (same with Ubuntu) and goes black but flashes something that says about KVM disabled by bios.

This is on an Asus C300. I would appreciate any help you can give. This needs to be done before Christmas.

**Comment by reynhout** [comment]
Is QUAWKS your hardware ID? There are several variations on the ASUS C300 base model.

If QUAWKS, your processor is an N2830, which does support VT-x, but it might not be enabled in firmware. That could explain the message.

What firmware are you running (vendor and type)?

What happens after the KVM message? Did you try switching virtual terminals? (Ctrl+Alt+F2, etc)

**Comment by taylorsangrey** [comment]
When the KVM message is showing the screen keeps refreshing like it is trying to restart it as a fallback. And I have tried different terminals. Also, it is TERRA. I think.

https://www.amazon.com/gp/product/B01M72MG4V/ref=oh_aui_detailpage_o00_s01?ie=UTF8&psc=1

**Comment by taylorsangrey** [comment]
N3060

**Comment by reynhout** [comment]
OK, the C300SA is TERRA13. The N3060 processor supports VT-x as well.

What is on the other terminals? Do you have a login prompt?

What firmware are you running (vendor and type)?

**Comment by taylorsangrey** [comment]
VT-x? Sorry, I am literate with this stuff, but not like expert....

The terminals appear to switch, but I am not sure.... it flickers too fast. And the login prompt seems to be there.

And firmware like distro?

**Comment by reynhout** [comment]
VT-x is the CPU tech that KVM requires. It also needs to be supported in firmware to work. But I think the KVM message is a red herring, so let's ignore that for now.

It sounds like the windowing system is failing to start, and retrying repeatedly.

TERRA13 is a Braswell, so you need to flash firmware to boot Linux. See https://github.com/reynhout/chrx#compatibility and https://wiki.galliumos.org/Firmware. The instructions for chrx link to a script and firmware by MrChromebox, but the other possibility is a script and firmware by John Lewis.

**Comment by taylorsangrey** [comment]
I already used MrChromebox's thing and did option number 1 which is RW_LEGACY before I even used this script.

**Comment by reynhout** [comment]
OK, then it sounds like everything should be set up properly.

TERRA13 is a new-ish device though, and there aren't a lot of field reports yet. I'd suggest asking for help on Reddit, to see if anyone has had a similar problem. https://reddit.com/r/GalliumOS or https://reddit.com/r/ChrUbuntu.

The only GalliumOS issue report I can find for TERRA13 is asking about keyboard behaviour, post-install, which suggests that user didn't run into the same problem. I'm not sure whether they installed with chrx or from ISO. There shouldn't be a difference, but it can't hurt to try -- just make sure you do not let the installer repartition your drive, or you'll lose ChromeOS. The Braswell ISO is in https://galliumos.org/releases/nightly. Instructions are at https://wiki.galliumos.org/Installing.

**Comment by taylorsangrey** [comment]
Wait, so I can do the traditional way of installing linux? Like I don't care for Chrome OS at all to be honest....

**Comment by reynhout** [comment]
Sure, if you don't want to dual-boot, just install from ISO.

**Comment by taylorsangrey** [comment]
I updated my comment.

**Comment by reynhout** [comment]
The firmware updater tool can be run from ChromeOS or Linux. And anyway you've already run it, so that's done.

**Comment by taylorsangrey** [comment]
Since I already installed chrx though, before I install via ISO wouldn't I have to restore to get rid of the partitioning done by chrx? Since I don't have a seaBios screen at all....

**Comment by reynhout** [comment]
No. The installer is capable of repartitioning the drive. It will prompt you.

But what do you mean you don't have a SeaBIOS screen? You should have a white "OS verification is OFF" screen, press Ctrl+L, then get a SeaBIOS banner at the top of the screen.

**Comment by taylorsangrey** [comment]
I get the white screen and press Ctrl + L and it just goes straight to Gallium or whatever OS I install.

**Comment by reynhout** [comment]
Hm, I haven't seen that on Braswells or any other models. Regardless, you do have SeaBIOS. It might not display the banner (or only do so very quickly) if you only have a single bootable device, but you'll be prompted to press Esc to select which device to boot from, if there is more than one.

**Comment by taylorsangrey** [comment]
Okay I will report back within a few minutes.

**Comment by taylorsangrey** [comment]
Same thing although the Gallium boot splash took longer so I think it by default booted my external drive. No seaBios though.

**Comment by reynhout** [comment]
When you flashed your firmware, you should have been given a choice of boot device prioritization, internal or USB/SD.

If you don't see the SeaBIOS banner, you might also not see the prompt to pick a boot device. That might mean that the firmware is having trouble setting up a graphics mode, and a similar problem might explain why X11 is failing to start.

But the delay might just be a timeout before it selects the internal drive again. So I'm not sure you've been able to test both yet.

If you can still boot ChromeOS, you can mount the Linux partition to examine logfiles:

    mkdir /tmp/a
    sudo mount /dev/mmcblk0p7 /tmp/a
    more /tmp/a/var/log/syslog
    more /tmp/a/var/log/Xorg.0.log

**Comment by reynhout** [comment]
You might also try John Lewis's firmware. If something changed recently in MrChromebox's firmware that is causing a problem setting the video mode, it's possible that John's would have better luck. Link from the GalliumOS wiki Firmware page.

After that, I'm out of ideas. Next stop, Reddit.

**Comment by taylorsangrey** [comment]
This is where it looks like it went to hell....

[    53.321] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
[    53.321] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
[    53.321] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    53.321] (II) FBDEV: driver for framebuffer: fbdev
[    53.321] (II) VESA: driver for VESA chipsets: vesa
[    53.321] (WW) xf86OpenConsole: setpgid failed: Operation not permitted
[    53.321] (WW) xf86OpenConsole: setsid failed: Operation not permitted
[    53.321] (WW) Falling back to old probe method for modesetting
[    53.321] (WW) Falling back to old probe method for fbdev
[    53.321] (II) Loading sub module "fbdevhw"
[    53.321] (II) LoadModule: "fbdevhw"
[    53.321] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    53.321] (II) Module fbdevhw: vendor="X.Org Foundation"
[    53.321]    compiled for 1.18.3, module version = 0.0.2
[    53.321]    ABI class: X.Org Video Driver, version 20.0
[    53.321] (WW) Falling back to old probe method for vesa
[    53.322] (EE) No devices detected.
[    53.322] (EE) 
Fatal server error:
[    53.322] (EE) no screens found(EE) 
[    53.322] (EE)

**Comment by taylorsangrey** [comment]
Also, I already tried John Lewis's firmware and the script said mine is unsupported.

**Comment by taylorsangrey** [comment]
And sorry for yet another comment, but I made a Ubuntu iso installer drive and it default boots to that drive. No seabios or anything of the sort. Although will check this for your replies in the morning as I am going to sleep.

**Comment by reynhout** [comment]
SeaBIOS is definitely there, just no visible banner. I'd check in with MrChromebox next, and post to Reddit.
