### ISSUE TITLE
chrx.org/chrx-install latest version?

### ISSUE THREAD

**Issue by uaau** [reynhout/chrx#3]
I'm getting 1.1.3 when running curl -Is https://chrx.org/go && bash go

What's the best way to fetch 2.0.0?

Thanks!

**Comment by reynhout** [comment]
chrx 2.0 hasn't been released yet. But it is ready, just waiting to sync with the GalliumOS release schedule.

You can get 2.0 by switching to the secret "dev channel":

    chronos@localhost ~% export CHRX_WEB_ROOT="https://chrx.org/dev"
    chronos@localhost ~% curl -Os $CHRX_WEB_ROOT/go && sh go

Note that this is *usually* not a good idea (I'm often breaking things there), but you'll be fine this time. :)

**Comment by uaau** [comment]
Oooh! Thanks!
