### ISSUE TITLE
Reinstalling galliumos via chrx does not ask for partion size

### ISSUE THREAD

**Issue by madsheilskov** [reynhout/chrx#32]
I have previously had a dual boot galliumos/chromeOS on my Dell Chromebook 13 using Mrchromebox Legacy boot and installed via chrx. I decided the partition left for chromeOS was to small, and went through restoring firmware boot, and wiped the computer with chromeOS recovery tool and exited Developer mode.  However, I cannot reclaim the original partition again, and so I am stuck with the to-large partition for Galliumos. When using chrx it does not allow me to set partition sizes as it did in the initial install. Any idea how to solve this. Can you force the chrx installer into partitioning, and how come it doesnt ask the second time.?
Thanks.

**Comment by reynhout** [comment]
The ChromeOS Recovery tool will restore all partitions. Are you sure you didn't do a Powerwash instead?

The Recovery Image is downloaded and installed on a USB drive, then booted by pressing Ctrl+F3+Power. It completely removes everything on the internal storage, including the old ChromeOS partitions and the GalliumOS partition.

**Comment by madsheilskov** [comment]
Yes I did that from Google's recovery util app here: [https://chrome.google.com/webstore/detail/chromebook-recovery-utili/jndclpdbaamdhonoechobihbbiimdgai] for Dell Chromebook 13 7310 (Lulu). It has worked previously. Of note however it repeatedly failed to download and create the recovery image from the chromebook itself ("download/connection failed" or something like that, I tried several USB sticks) and I had to make it from another PC. Is this "behaviour" intended ?. 
When I boot from the recovery image it seems to begin the process for a couple of seconds but then reboots and starts over.

**Comment by reynhout** [comment]
It sounds like your Recovery is failing, or not running to completion.

It usually takes a few minutes to run, and of course when it does, the
internal storage is fully reset to factory state.

I always download Recovery images directly -- the Recovery Image Tool
doesn't seem to work reliably.

For LULU:

https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_8743.85.0_lulu_recovery_stable-channel_mp-v2.bin.zip

Unzip, then write the bin file to a USB drive just like you would write
an ISO. There's a good guide for writing to USB here:

https://wiki.galliumos.org/Installing/Creating_Bootable_USB

Hope that helps!

**Comment by madsheilskov** [comment]
Thats a great suggestion - I will give it a try later, and get back with an update. Thanks!
