### ISSUE TITLE
Partitioning during installation

### ISSUE THREAD

**Issue by lrdmora** [reynhout/chrx#34]
First of all, fantastic job.  I have 3 or 4 Linux chromebooks including a Dell 13 which I am running either Galliumos or Ubuntu 16.04.  Here's the issue I'm coming up against.

My Dell 13 is a very high end ChromeBook, I swapped out the drive for a 256GB SSD that makes this little machine, considering the IPS touch screen, better than either of my two Macbook Airs.  It bascially buries them while looking fantastic at the same time.  Huge battery life, great form factor, amazing screen.  I'd like to dual boot since I want to mess around with Android Apps on the Chrome OS partition.

Here's my issue and maybe I'm doing something wrong.

1.  When you go to partition it asks you how much you want for your Linux partition, the first time around it told me 233GB and I thought okay that will leave me 16GB and thats enough for a system I won't actually be using all that much.  When I opened up my Chrome I had 1.9GB and kept getting out of space errors.

2.  I wiped my drive with Gparted Live, reinstalled Chrome, double checked my space and I have 233GB free.  Redid my Chrx install and selected 200GB for the Linux partition and rebooted.  Opened up Chrome and I have. . . 1.9GB free. 

3.  I also tried this with a Dell 11 I have lying around and used the -t to install on the 128GB USB 3 stick (I've done similar Ubuntu installs using that stick multiple times works fine).  Same issue with not the USB but my 16GB SSD which shouldn't have been touched.  1.9GB storage in my Chrome system.  At the time I thought I targeted the wrong drive, but my Sticks Activity LED was flashing etc.  and I checked and I had it sent to the right place. 

4.  So I opened Gparted and found out that the "missing" 34GB had been partitioned off into it's own partition as a EXT4 (which I'm assuming is okay since Chrome is Linux).  

So what am I doing wrong here?  It appears that the partitioning is "clipping" any free space over 1.9GB on the chrome system and setting it aside even if I am not using it on the Linux install.

Also why did it partition my SSD during the USB install?

**Comment by lrdmora** [comment]
Okay I feel like an idiot, items 1-2 are resolved, I didn't realize that when you sign into your chrome account as a Guest it automatically gives you 1.9GB of space.  I had a light bulb moment when I thought to myself wasn't the space 1.5GB on the fist install not 1.9?  Signed in as myself and 34GB.

But still have a couple of questions.

1.  Chrome OS says I have 217GB but the Linux Partitioning says 233GB free.  Why is this?

2. I'm going to redo the install to USB I'm guessing I did SDA1 when maybe it should have been SDB.  Not sure.

**Comment by reynhout** [comment]
@lrdmora Yes, the Guest account can be confusing. It's all there though.

You can check from either ChromeOS or other Linux with `lsblk`. ChromeOS reserves two 2GB partitions for the OS (KERN-A and KERN-B). Several other smaller partitions, and then one primary data partition (which I think will always be partition 1).

Re: your remaining questions:

1. I'm guessing those measurements are from different sources, and are using different units. 233 Gigabytes (GB) = 216.998 Gibibytes (GiB).

2. chrx should not perform any operations at all on non-target disks, but I'll take a look to see if I can find a problem.

**Comment by reynhout** [comment]
I can't find any issues relevant to item 2, above. Closing for now, please re-open if the problem persists.
