### ISSUE TITLE
Directly after installation

### ISSUE THREAD

**Issue by padilla-uly** [reynhout/chrx#35]
I'm running Samsung's Chromebook running on an Intel CPU.

I have finished the installation process and am just a bit lost on how to boot up the GalliumOS.

So I'm a basic user but i figured all i would need to do is hit "ctrl + alt + 'right arrow'" to switch window, punch in "chrx" for localhost login, but the terminal deemed my login/pw unrecognized. So whats the next step directly after installation?

**Comment by reynhout** [comment]
At the white "OS verification is OFF" screen, press Ctrl+L for GalliumOS (Legacy Boot), or Ctrl+D for ChromeOS.
