### ISSUE TITLE
Is there a way that I dont have to press L every time I reboot?

### ISSUE THREAD

**Issue by xKim** [reynhout/chrx#39]
I am wondering if there is a way that I don't have to press L every reboot. It is very inconvenient. But I still want to keep my galliumos installed with chrx.

**Comment by hmrubin** [comment]
@xKim I don't know of a way to do this if you want both chrome os and gallium installed. However if you only have linux it is quite easy (from what I understand from mrchromebox's website)

**Comment by reynhout** [comment]
@xKim See https://wiki.galliumos.org/Firmware and https://mrchromebox.tech/
