### ISSUE TITLE
Fedora Wifi Stopped Working

### ISSUE THREAD

**Issue by hmrubin** [reynhout/chrx#41]
Not sure if this is a chrx fedora issue or not but after 48 hours of having fedora installed the wifi indicator completely disappeared and the Chromebook no longer recognizes wifi

**Comment by reynhout** [comment]
Almost definitely not a chrx issue. Chrx is just an installer. When installation is finished, chrx is no longer a part of your system.

Does Fedora use Network Manager? We see occasional problems with NM on GalliumOS, it's not the most reliable bit of kit. :(
