### ISSUE TITLE
Ubuntu on LULU

### ISSUE THREAD

**Issue by partisanyc** [reynhout/chrx#44]
Hi, 

Thank you for the amazing software. I successfully install GalliumOS on my Dell Chromebook 13 (i5) some time ago, but today I attempted to install Ubuntu standard and Desktop versions on the same machine. I ended up getting messages like the following (pasted from another forum) while attempting to boot:

[    4.479134] [drm:intel_dp_link_training_clock_recovery [i915]] *ERROR* too many voltage retries, give up
[    4.479655] [drm:intel_dp_link_training_channel_equalization [i915]] *ERROR* failed to train DP, aborting

Using Ctrl+Alt+F1, I was able to log into Ubuntu and shut down, but was not able to progress past that error. I reinstalled GalliumOS and am using that to write this message, but wondering if/how I can install Ubuntu 16.04. 

Any help is appreciated and I am happy to attempt any installations you might require.

**Comment by partisanyc** [comment]
Logging into GalliumOS today, I decided to Ctrl+Alt+F1 at the login screen. In the startup log, I see the same errors, but in this case, it is able to progress past that error.

**Comment by reynhout** [comment]
I see the messages also on GalliumOS on LULU.

I have never tested Ubuntu on LULU. What version did you try?

**Comment by partisanyc** [comment]
@reynhout I see the messages as well on GalliumOS, but it makes it to the login screen so I didn't notice. With Ubuntu, it doesn't get past that message. 

I installed 16.04 standard using the command provided:

`cd ; curl -Os https://chrx.org/go && sh go -d ubuntu -e standard -r 16.04 -H hal -U dave -p admin-misc`

I also tried desktop instead of standard.

**Comment by reynhout** [comment]
@partisanyc OK, thanks for the info. FWIW, I suspect the messages are not related to the boot failure. But we'll see.

**Comment by partisanyc** [comment]
I tried various things that day so I can't be certain, but it might be related to GRUB configuration. I attempted to boot from grub recovery, but was unable to do so. Hopefully that does help.

I am happy to test any fixes.

**Comment by wilsonehusin** [comment]
Any updates on this? I had an out of date GalliumOS and I decided I want Ubuntu instead so I just wiped my GOS and install Ubuntu, now I'm here...

When I do Ctrl + Alt + F1 I can get into console and do stuff, though my WiFi card was not detected so I couldn't try more things until I get my hands to some external drive via USB.

**Comment by reynhout** [comment]
Tecent Ubuntu kernels fail to init video on LULU with RW_LEGACY firmware. They succeed on LULU with full ROM firmware.

I won't be able to fix Ubuntu kernels! So until/unless it's fixed upstream, Ubuntu on LULU (and possibly other models) might be a dead end.

GalliumOS fixes the issue in our kernels, of course. :)
