### ISSUE TITLE
No sound in Fedora 25 on Chromebook Pixel 2015

### ISSUE THREAD

**Issue by grdo787** [reynhout/chrx#45]
I recently installed Fedora 25 using chrx and all works fine except that there's no sound from the speakers. I looked around for a solution but I didn't found one.

**Comment by reynhout** [comment]
I don't think Fedora will have the necessary kernel patches for audio on SAMUS.

As far as I know, GalliumOS is the only distro with working audio OOTB on SAMUS today.

**Comment by grdo787** [comment]
Is there a workaround. I try to compile a kernel using linux-samus scripts but that not work in Fedora.

**Comment by reynhout** [comment]
I've never built a kernel on Fedora (or with Fedora config), but the usual process should apply.

Or you can wait for an official Fedora kernel which includes the patches. They are in mainline now, so if the Fedora config enables the modules, you will get them automatically.

If you're in a rush, Bluetooth/USB audio should work on Fedora. Or, just install GalliumOS instead. :)

**Comment by grdo787** [comment]
I tinker around with alsamixer and I got audio in both the speakers and headphones, but the headphone sound is very low though. I looked at the linux-samus script for sound and I did manually the configuration the script shows for alsamixer.

**Comment by reynhout** [comment]
@grdo787 Great. What kernel version?

**Comment by grdo787** [comment]
It is the kernel 4.10.13

**Comment by reynhout** [comment]
Good to know, thanks!
