### ISSUE TITLE
chrx, dd and USB

### ISSUE THREAD

**Issue by darren3** [reynhout/chrx#46]
Hello, I have Gallium OS installed on a USB drive. If I used chrx to partition my chromebook could I make a copy of my USB install using dd and install it on my chromebooks drive?

**Comment by reynhout** [comment]
@darren3 No, `dd` would not be the right tool to use.

If you just want to copy user data and possibly some system config, I'd go ahead and do the full install with chrx, then use `rsync` to copy the bits from USB that you need, e.g.:

```
mkdir /tmp/a
mount /dev/sdb1 /tmp/a
rsync -av /tmp/a/home/USERNAME /home
rsync -av /tmp/a/etc/CONFIGDIR /etc
```

It will greatly simplify things if your username is the same on both installations. And obviously be careful not to trash any system-specific config if copying any files from `/etc`.

**Comment by darren3** [comment]
Thanks for your help, rsync worked well.

**Comment by reynhout** [comment]
Sure thing. :)
