### ISSUE TITLE
Need help getting back into Linux partition.

### ISSUE THREAD

**Issue by Lykie** [reynhout/chrx#47]
Basically I went and updated GalliumOS and didn't update grub properly which is now preventing me from booting into it. I think I just need to reinstall grub so I thought to try to use the installer to install the grub partition again or something. After booting it up I got this

chronos@localhost / $ cd ; curl -Os https://chrx.org/go && sh go
chrx installer, version 2.4.1

    Hardware ID: CELES_D25-B4A-F8A-A9K
    Model:       Samsung Chromebook 3
    Released:    2016
    CPU Family:  Intel Braswell
    Prognosis:   success likely, ONLY IF FIRMWARE HAS BEEN UPDATED!

Checking hardware support for legacy boot...  OK
Setting up target disk /dev/mmcblk0...

Installing to /dev/mmcblk0p7...
Found a dos partition table in /dev/mmcblk0p7
Proceed anyway? (y,n) 

What should I put in, and what should I do to reinstall grub?

**Comment by reynhout** [comment]
Don't do any of that.

Do this: https://www.reddit.com/r/GalliumOS/comments/5mhjd3/acer_14_wont_boot_after_grub_update/dc3o3iv/?st=iyx72g0o&sh=e942f15b

**Comment by Lykie** [comment]
For some reason I ended up with an error at the chroot commands with no previous error.

chronos@localhost ~ $ sudo bash
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mkdir /tmp/a
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # GALLIUMOS_ROOT=/dev/mmcblk0p7
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount $GALLIUMOS_ROOT  /tmp/a
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount -o bind /proc    /tmp/a/proc
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount -o bind /dev     /tmp/a/dev
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount -o bind /dev/pts /tmp/a/dev/pts
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount -o bind /sys     /tmp/a/sys
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # mount -o bind /run     /tmp/a/run
localhost u-1b95088fd3adbaa73192abb16574c545c8be38bd # chroot /tmp/a /bin/bash
groups: cannot find name for group ID 11
groups: cannot find name for group ID 207
groups: cannot find name for group ID 208
groups: cannot find name for group ID 219
groups: cannot find name for group ID 1001
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

root@localhost:/# sudo chroot /tmp/a /bin/bash
chroot: cannot change root directory to '/tmp/a': No such file or directory

**Comment by reynhout** [comment]
You only need to `chroot /tmp/a /bin/bash` once. The first time you did it (when your prompt changed) it worked correctly. Those messages about group names are not errors.

**Comment by Lykie** [comment]
When running sudo apt-get install grub I get this

oot@localhost:/# sudo apt-get install grub
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  grub-pc-bin libgles1-mesa libmircommon5
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libc6-i386
Suggested packages:
  grub-legacy-doc mdadm
The following packages will be REMOVED:
  grub-gfxpayload-lists grub-pc grub2-common
The following NEW packages will be installed:
  grub libc6-i386
0 upgraded, 2 newly installed, 3 to remove and 0 not upgraded.
Need to get 2,529 kB of archives.
After this operation, 9,489 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libc6-i386 amd64 2.23-0ubuntu9
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 grub amd64 0.97-29ubuntu68
  Temporary failure resolving 'archive.ubuntu.com'
Err:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libc6-i386 amd64 2.23-0ubuntu9
  Temporary failure resolving 'archive.ubuntu.com'
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-i386_2.23-0ubuntu9_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/grub/grub_0.97-29ubuntu68_amd64.deb  Temporary failure resolving 'archive.ubuntu.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Trying to update or fix-missing result in nothing still.

**Comment by Lykie** [comment]
Okay I've done it Thanks for helping me out kind dude, I'll make sure never to make this mistake again now.
