### ISSUE TITLE
Can't re-partion without wrecking Chrome OS

### ISSUE THREAD

**Issue by Agent-Cain** [reynhout/chrx#48]
I wanted to re-partition the new partition to have space to install an other distro on the ssd. 
What ever I try to do, I end up with chrome os out of order.
Is it my fault or just not possible ?
My plan was having 3 other debian based distros beside chrome os ...

**Comment by reynhout** [comment]
That's correct. ChromeOS partitions require special handling. Chrx uses the ChromeOS partitioning tool (`cgpt`) for this reason. As far as I know, no other partitioner will work.

**Comment by Agent-Cain** [comment]
Ok, then I will try it again with cgpt. 
But what I was doing was repartitioning the Ubuntu Partition, so I don't get where the problem is ..

**Comment by reynhout** [comment]
Any partitioning tool will have to rewrite the partition map for the whole disk, which breaks ChromeOS if not done properly.

**Comment by Agent-Cain** [comment]
Do you have a cgpt guid or something like that ?
Maybe it's too late, but i can"t get it working ...

**Comment by reynhout** [comment]
> Do you have a cgpt guid or something like that ?

Do you mean "GUID", or "guide"?

If the latter, try running `cgpt` or `cgpt --help`. There's some way to coax basic usage info out of the binary, which is what I used. There might be more formal docs somewhere, but I didn't look.

If the former, I don't know the GUID of ChromeOS partitions, but you should be able to extract it from a working ChromeOS map.

**Comment by Agent-Cain** [comment]
I was looking for a guide, sorry.

**Comment by Agent-Cain** [comment]
okay, now I was able to make a new partition without crashing chrome os, and reinstall ubuntu with your script.
Now there is a big space unallocated and when I try to install a new distro, every distro tries to set up new partitions ... which won't work obviously.
Do you have any tips to go further ?

**Comment by reynhout** [comment]
I don't know what distros you're trying to install, but there should be an option to install to an existing partition. I know the Ubuntu installer (Ubiquity) is obvious about it, maybe others are less clear?

**Comment by Agent-Cain** [comment]
Right now I'm trying to install elementaryos besides ubuntu

**Comment by Agent-Cain** [comment]
Maybe I made the repartition job wrong.
The new partitions file system is always unknown, not ext4. Additionally  elementary os creates a linux swap partition, which I also couldn't set up with cgpt.

**Comment by Agent-Cain** [comment]
Okay, now I'm a step nearer to my goal:
mkfs & mkswap both work without messing up chromeos. 
I was able to make 2 partitions and could install elementary os on one of them, on the other should be ubuntu but i can't see it or choose it ...
ctrl + d brings me to normal working chromeos 
ctrl + l brings me into elemantary os 

if I could swap now between ubuntu and elementary os, everything would work like I'd like to !

**Comment by Agent-Cain** [comment]
Wow a long journey ends :D 
Everything is no working fine.
Thanks again for your tip with cgpt
