### ISSUE TITLE
Curl No URL Specified

### ISSUE THREAD

**Issue by GamerMan7799** [reynhout/chrx#5]
I'm trying to reinstall Lubuntu on my ChromeBook Acer 270. But after running the script and getting getting the partitions set up. It will say
 
```
Fetching Lubuntu core image file... 
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
The full install log can be found [here](http://pastebin.com/L1nEGWb5)

I appreciate the help.

**Comment by reynhout** [comment]
Oops, sorry about that! I'll fix it ASAP.

In the mean time, you might try GalliumOS instead (`-d galliumos`), I know that one works as of a few minutes ago, and you might like it better!

But I'll have that error fixed first thing tomorrow.

Thanks for the report.

**Comment by GamerMan7799** [comment]
GalliumOS is installing. Thank you. 
Quick question though, if I decide I don't like GalliumOS, can I use your script to replace it or will I have to restore ChromeOS and redo everything?

**Comment by reynhout** [comment]
Yes, chrx can replace any OS it installs -- just run it again. No need to revert to ChromeOS.

**Comment by reynhout** [comment]
Fixed and added better error checking. Please let me know if you have any further trouble. Thank you again for the report!
