### ISSUE TITLE
re: repartition disk chromebook - cb3-111 - gnawty

### ISSUE THREAD

**Issue by Sapper-1cd** [reynhout/chrx#50]
Hello-  
I am unable to recover my chromebook.  I would like to remove the chrx partitions and recover the space.  Could you give me a suggestion to do this?  I am aware of the risks.  Thank you.

Enclosed are (2) screenshots that may be helpful.  Sorry I am new to this.
![screenshot 2017-08-27 at 09 56 55](https://user-images.githubusercontent.com/16266283/29752625-b6d5e5e4-8b16-11e7-9383-6dc331268f42.png)
![screenshot 2017-08-27 at 09 58 06](https://user-images.githubusercontent.com/16266283/29752631-e66b1fc2-8b16-11e7-8135-6fe804a7e5a5.png)

I have tried researching, via Dennis L and prior questions using the following commands:
cgpt add -i 6 -t unused /dev/sda
cgpt add -i 7 -t unused /dev/sda
cgpt add -i 1 -s $(( $(cgpt show -i 1 -s /dev/sda) + $(cgpt show -i 6 -s /dev/sda) + $(cgpt show -i 7 -s /dev/sda) )) /dev/sda

but when I use #1 above I get no file.  Can you help me out?  Thanks much.  Chrx is great.

Regards,

Eric

**Comment by reynhout** [comment]
There aren't any "risks" to Recovering ChromeOS. The intention of Recovery is to completely erase the contents of internal storage and replace it with a factory ChromeOS image.

All you need to do is download a ChromeOS Recovery Image from Google, write it to USB/SD, invoke the Recovery key sequence (Esc-Refresh-Power), and follow the instructions on screen. Full docs: https://support.google.com/chromebook/answer/1080595?hl=en

So, I'm not sure what you're trying to do, or how to answer your question. :) Can you restate?

PS: You screenshots do not display for me -- if they are required to understand the question, perhaps try Imgur or similar?

**Comment by Sapper-1cd** [comment]
Thank you for the chrome recovery tips.  My question was in regards to attempting to remove Chrx via re-partitioning or clearing out the areas (space allocated to Chrx).  See issue # 11 from Dennis L (closed)-- ability to remove the Linux partition.  I was attempting to work with that response but have been unsuccessful.  I can do a full recovery as you suggest, however I wanted to attempt to remove the Linux partition without full recovery.

**Comment by reynhout** [comment]
Those command lines will need to be altered for some Chromebook models. If your model has eMMC storage, the paths will be `/dev/mmcblk0` instead of `/dev/sda`.

The whole process remains untested, but it looks like it should work.

ChromeOS Recovery is quick and painless, so that's the simplest recommendation. If you have local storage, you can back it up first.

**Comment by Sapper-1cd** [comment]
Thank you for the correct path.  I will try that.  Much appreciated.

**Comment by Sapper-1cd** [comment]
I ran the above command (sudo cgpt add -i 1 -s $(( $(cgpt show -i 1 -s /dev/mmcblk0) + $(cgpt show -i 6 -s /dev/mmcblk0) > + $(cgpt show -i 7 -s /dev/mmcblk0) )) /dev/mmcblk0) as root and it worked fine.  However upon running command - -  localhost dev # blockdev --rereadpt /dev/mmcblk0, i am getting the following error:
blockdev: ioctl error on BLKRRPART: Device or resource busy.  Thanks again for the help.  

Eric

**Comment by reynhout** [comment]
Command should be:

```
sudo bash
cgpt add -i 1 -s $(( $(cgpt show -i 1 -s /dev/mmcblk0) + $(cgpt show -i 6 -s /dev/mmcblk0) + $(cgpt show -i 7 -s /dev/mmcblk0) )) /dev/mmcblk0
```

Your pastes have spurious `>` chars in them, which might be causing a problem. Also you need to run as root, don't use `sudo` in the `cgpt` command line. I added `sudo bash` at the top to be more clear.

If it did work correctly, the `blockdev` error is not necessarily a problem. The device is, in fact, busy. Rebooting and then pressing Ctrl+D should kick ChromeOS which should notice the partition change and do its thing.

**Comment by Sapper-1cd** [comment]
With cgpt add -i 1 -s $(( p1 + p6 +p7)) /dev/mmcblk0, returning Error: Entry outside of valid region
Error:-i 1 -s 40988672

**Comment by reynhout** [comment]
OK, try rebooting into ChromeOS and then running the last step post-reboot:

```
cgpt add -i 1 -s 40988672 /dev/mmcblk0
```

**Comment by Sapper-1cd** [comment]
Still returning same error:
cgpt add -i 1 -s 40988672 /dev/mmcblk0
ERROR: Entry outside of valid region
ERROR: -i 1 -s 40988672

**Comment by reynhout** [comment]
Try reducing the size. Start with 40988670, then go from there.

Check the current size with `cgpt show -i 1 -s /dev/mmcblk0`. Somewhere between 40988672 and the current size should work.

**Comment by Sapper-1cd** [comment]
I ran again the original commands (with the spur) and it was accepted.  Then upon running the blockdev command again yielded same error as before.  Then I ran cgpt show -I 1 -s /dev/mmcblk0 and it showed size of 1.  I believe then I rebooted and it gave me the message "Your system is repairing itself.  Please wait."  It is now cycling through this same message with spinner for the 4th time.  It runs for 5 minutes each time and then when I press control-d it appears to just recycle over again.  Update.

**Comment by reynhout** [comment]
If `cgpt show -i 1 -s /dev/mmcblk0` shows size 1, then some command has not worked properly.

I'd move on to ChromeOS Recovery at this point.

**Comment by Sapper-1cd** [comment]
Thanks for all the input, information, and help @reynhout.  It appears I bricked it, but that is okay.  It was worth a shot.  Any suggestions for a usb / sd?  I had written chrx to my internal drive.

**Comment by reynhout** [comment]
There are some good low-profile USB drives listed here: https://wiki.galliumos.org/Buyers_Guide. I like the Samsung best for a permanent mount (gets hot but not too bad, very fast, no LED) or the Lexar for a utility device (good temp, half the speed, LED is quite bright). The SanDisk gets too hot and is a bit slower than Samsung in my testing. SanDisk was also the only one of the three to fail on me (after several hundred writes of GalliumOS ISOs :)

**Comment by Sapper-1cd** [comment]
Thanks for all the input.  Awesome.  I will check out the Samsung.

**Comment by Sapper-1cd** [comment]
I did purchase the Samsung USB drive you suggested and the instructions given worked perfectly.  I successfully recovered my Chromebook.  Thank you for all the help!
