### ISSUE TITLE
Ubuntu internal input issues on CELES chromebooks

### ISSUE THREAD

**Issue by bhjohnp1** [reynhout/chrx#51]
Good news -- There are no issues that I can see running the full Ubuntu image on my Celes Samsung chromebook (Braswell model). However, the internal keyboard and mouse function are almost entirely useless. The keys stick, the mouse will stop moving, and it takes quite some time for them to become responsive again and then failing almost immediately after. Rinse and repeat. Interestingly enough, using an external mouse and keyboard is perfectly fine. Is there a fix for this I'm just not aware of? I'm only posting this as an issue because I could not seem to find a fix for my particular model. Hopefully I'm just blind. Thanks for any and all help! 

EDIT: I am very new to this kind of stuff, please don't murder me

**Comment by reynhout** [comment]
This is a known issue in mainline kernels.

We fixed it in the GalliumOS kernel many months ago (almost a year?), but I'm not sure if other distros have caught up yet. :)

Quick fix: install GalliumOS. More work: test the newest kernels you can find for Ubuntu.

**Comment by bhjohnp1** [comment]
Actually, the newest kernel available right now did the trick! Installing the newest mainline kernel fixed mouse movement and keyboard response. Working on finding how to get the track pad clicking to function now. Will edit this post if its an easy solution.

**Comment by reynhout** [comment]
The CELES trackpad click issue requires another kernel patch. Again, fixed in GalliumOS.

You can run the GalliumOS kernel on Ubuntu, but we usually recommend installing `ubuntu-desktop` on GalliumOS if you just want the Ubuntu desktop env.

**Comment by bhjohnp1** [comment]
You've got me figured out. Thanks for helping me out with that. And thanks for the speedy reply as well. Hopefully when I'm not as useless using Linux I can contribute more to projects like this.

**Comment by reynhout** [comment]
Good luck. And I hope Ubuntu fixes this issue in their kernels!
