### ISSUE TITLE
Touchpad doesn't work on Pixelbook

### ISSUE THREAD

**Issue by ucmucm** [reynhout/chrx#52]
I have tried many desktop environments, but the touchpad always doesn't work.
Can anyone help me?

**Comment by Agent-Cain** [comment]
Have you tried to push it harder ? Does it work work if you push harder ? 
Seems like a stupid questions, but there was a similar problem with some acer chromebook 14.
Maybe the same fix will work for you ?!

**Comment by reynhout** [comment]
This will need to be fixed in the distros, not in chrx. Closing this ticket for now.
