### ISSUE TITLE
Acer c720 Kubuntu install - with 64GB SSD; is there a way to increase swap size

### ISSUE THREAD

**Issue by reywang18** [reynhout/chrx#53]
Usage: chrx [ option ... ]

Can we have an option to set swap size?
I tried -a i386; due to Line chat app. And notice Google Chrome has 64-bit no such 32-bit.

**Comment by reynhout** [comment]
GalliumOS (and ChromeOS) use zram as swap, which doesn't require a partition on the disk.

You can create and add a swapfile to the filesystem any distro though, which is a better option for dual-boot, given ChromeOS's multiple-partition requirements.
