### ISSUE TITLE
Fedora opens at terminal after boot.

### ISSUE THREAD

**Issue by limegorilla** [reynhout/chrx#56]
Right, I install fedora, like this:
`##standard command## -d fedora -e kde `
And it takes a small while, and appears to install correctly. BUT, when I boot, it opens up at a bash command line.
Any ideas?
I know I can install the KDE environment via command line, but I have NO idea on how to connect to WiFi through terminal.

**Comment by reynhout** [comment]
I just merged a PR from @jedigo that might be related to this issue. I'm not 100% certain, but hopefully he can clarify for us.

PR: https://github.com/reynhout/chrx/pull/55/commits/11d55473403120bb12cb4d095468c315a6e92524

**Comment by jedigo** [comment]
Yes, that was the issue the pr should fix.

In the meantime, you can fix an already installed desktop environment by enabling and starting the display manager.

The display manager depends on the desktop that was installed; for KDE it is sddm, for gnome it is gdm, for most others it is lightdm.

So, for KDE this should fix the issue, after logging in at terminal:

sudo systemctl enable sddm
sudo systemctl start sddm

I am on mobile right now, so hopefully these are the correct commands; if not I'll correct it later today.

**Comment by reynhout** [comment]
@jedigo Thank you!

@limegorilla Please let us know if this sorts it out for you.

**Comment by limegorilla** [comment]
@jedigo @reynhout 
I'm just re-installing now, and will get back in a moment....

**Comment by limegorilla** [comment]
Ok - It worked! The commands you provided @jedigo worked fine.
