### ISSUE TITLE
Request: Option to wipe existing rootfs before installing new OS

### ISSUE THREAD

**Issue by shinji257** [reynhout/chrx#6]
I would like to see an option that could be passed to make the script wipe the target roofs before installing the new OS in case you are switching.  At the moment it doesn't appear to be doing that?

**Comment by reynhout** [comment]
It should already do that, unless I misunderstand your description.

When using chrx to install a new OS (after having used it before to install a previous OS), chrx will make a new filesystem on the root partition (commonly `/dev/sda7`) before installing the OS. Anything previously in that partition should be cleared.

If that's not working, it's definitely a bug! Can you tell me what you've seen?

**Comment by shinji257** [comment]
Well I'll need to go back and recheck to see maybe it is just silent now but I wasn't seeing any messages for it before.  Also in late stages the xubuntu default settings package (galliumos) was complaining that it could not remove a folder because it wasn't empty but now that seems to just be a quirk of the package.  I'll close it for now then reopen it if there is an issue.  Sorry for the noise on this one!
