### ISSUE TITLE
keyboard not working in galliumos alpha

### ISSUE THREAD

**Issue by uygwfd254** [reynhout/chrx#61]
i have asus c300sa terra braswell with mr chromebox firmware. i installed galliumos 4.16.13, alpha, and after boot to the login screen, keyboard not working except the power off key.

**Comment by reynhout** [comment]
This has been reported on EDGAR with RW_LEGACY firmware as well.

The quick fix is to boot the `4.15.18-galliumos` kernel instead (version installed prior to latest update).

**Comment by uygwfd254** [comment]
oh, that's easy.
will this be fixed in future updates?

**Comment by reynhout** [comment]
Yes, GalliumOS 3.0final will either fix the issue, or roll back to 4.15.18 for Braswell models.

Notably, the issue does not occur on full ROM firmware.
