### ISSUE TITLE
No sound on Chromebook Pixel 2015 LS with Ubuntu 18.04

### ISSUE THREAD

**Issue by LonerSkywalker** [reynhout/chrx#63]
After installation, everything is fine except the sound.I have tried reinstall alsa, but it didn't work.

**Comment by LonerSkywalker** [comment]
ummm..The default version about GalliumOS in script is 2.1.How could I install the 3.0 version? and is the 3.0 version stable?

**Comment by reynhout** [comment]
Oh, sorry. GalliumOS 3.0 is still marked "alpha", but yes it's stable on all platforms.

To install with chrx, add the `-r dev` option to the command line, e.g.:

```
curl -O https://chrx.org/go && sh go -r dev [other options]
```

**Comment by LonerSkywalker** [comment]
OK,Thank you very much.The GalliumOS 3.0 is great!
