### ISSUE TITLE
SSL Expired

### ISSUE THREAD

**Issue by amendoyn** [reynhout/chrx#66]
Hi, I already have used chrx on my samsung chromebook 3. To manage better my internal storage, made a full chromeOS recovery. Installed again a Mrchromebox firmware, enable legacy and usb support. When I run (on Ctrl + Alt + F2 terminal) cd ; curl -Os https://chrx.org/go $$ sh go an error occurs. Its said a 23 error, SSL expired. Also, I tried to run with -k to make an insecure connection, but another error occurs:

curl: (23) Failed writing body (0 != 186)
curl: (7) Couldn't connect to server
curl: (6) Couldn't resolve host 'sh'
curl: (6) Couldn't resolve host 'go'

What is happen? Thank you, guys.

**Comment by reynhout** [comment]
Sorry, the certificate was updated but the webserver hadn't been restarted.

Should be fixed now. Thank you for the report!
