### ISSUE TITLE
Fedora 29 installation has no initramfs because dracut is not ran

### ISSUE THREAD

**Issue by TC01** [reynhout/chrx#67]
I just ran chrx to install Fedora 29 on a HP Chromebox (it was running Gallium previously-- also installed via chrx-- but I'm a Fedora user and wanted to run something closer to home). I was pleasantly surprised to discover chrx supported Fedora!

The only issue I ran into was that /boot didn't actually have a kernel image or initramfs in it, and so the system wouldn't boot out of the box. I was a bit puzzled by this at first; the internet suggested I should try reinstalling the kernel package in a chroot to force the RPM scriplets to run. But that didn't seem to help either.

Then I realized that I first needed to manually run dracut to generate an initramfs (/boot/initramfs-${uname}...). Once I did that, I was *then* able to reinstall the kernel and /boot/vmlinuz-${uname} was successfully created.

I don't know why this is not happening automatically during the installation, but I didn't look in detail to see how chrx handles installing Fedora. A quick workaround might be to do what I just did-- run dracut in the chroot and then reinstall the kernel-- after installing the core system [here](https://github.com/reynhout/chrx/blob/master/chrx-install#L988)? Anyway, I figured it was worth filing a ticket.

**Comment by jedigo** [comment]
Hi all, sorry for the long delay. This should be fixed in #84 

Please feel free to tag me if there are any issues with Fedora.

**Comment by reynhout** [comment]
Fixes in #84 merged and deployed to chrx.org. Thanks @jedigo!
