### ISSUE TITLE
fatal: unable to download and extract core image file.

### ISSUE THREAD

**Issue by masbrokemanaaja** [reynhout/chrx#69]
i got error when try to install gallium os version bismuth and 3.0

    Hardware ID: EDGAR_D25-A4C-S4I-A8O
    Model:       Acer Chromebook 14 (CB3-431)
    Released:    2016
    CPU Family:  Intel Braswell

> Press [enter] to confirm and continue: 
> 
> Fetching GalliumOS core image file...
> HTTP GET https://galliumos.org/releases/3.0/galliumos-generic-coreimage-3.0.tgz
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   169    0   169    0     0     82      0 --:--:--  0:00:02 --:--:--   120
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> fatal: unable to download and extract core image file.

i think must fix url path on chrx-install because folder 3.0 not exist on galliumos server and only 1.0 2.0 2.1 nightly

>     case "${CHRX_OS_RELEASE}" in
>     '1.0'|'1'|vivid)   CHRX_OS_VERSION="1.0" ;;
>     '2.0')             CHRX_OS_VERSION="2.0" ;;
>     '2.1'|'2'|xenon)   CHRX_OS_VERSION="2.1" ;;
>     '3.0'|'3'|bismuth) CHRX_OS_VERSION="3.0" ;; this line change to nightly

**Comment by reynhout** [comment]
3.0final isn't released yet, so it doesn't work as an arg to `-r`.

Try this command line: `curl -O https://chrx.org/go && sh go -r dev`

**Comment by masbrokemanaaja** [comment]
> 3.0 final isn't released yet, so those three values (`3.0|3|bismuth`) don't work yet as args for the `-r` switch. Using `nightly` would succeed, but would install the 2.1 nightly not 3.0.
> 
> For the GalliumOS 3.0 dev releases (which are very stable), use this command line:
> 
> ```
> curl -O https://chrx.org/go && sh go -r dev
> ```

ok thank you for information sir
