### ISSUE TITLE
GalliumOS: galliumos-laptop and galliumos-haswell fails during staging

### ISSUE THREAD

**Issue by shinji257** [reynhout/chrx#7]
When staging the packages fail to install.  I went into the chroot manually and it also failed but after doing an apt-get update it installed properly.

Error was that the package could not be found.

**Comment by reynhout** [comment]
OK, thank you. I'll see what happened.

**Comment by reynhout** [comment]
Thank you for the diagnosis. It should work now, but of course if you've installed them manually, you're all set.
