### ISSUE TITLE
tar: unexpected EOF in archive

### ISSUE THREAD

**Issue by rongreg** [reynhout/chrx#70]
Installing  galliumos get "unexpected EOF in archive" with both -r dev and -r nightly

I had Installed the RW_LEGACY firmware with  SeaBIOS firmware payload.

CHRX command used was;
     curl -O https://chrx.org/go && sh go -r dev -a i386
computer is;
   Brand Name 	Asus
   Series 	Chromebook
   Item model number 	C202SA-YS02
   Operating System 	Chrome
changed to -d ubuntu  and install went OK. 
final working command was;
 curl -O https://chrx.org/go && sh go -d ubuntu -e minimal -a i386

I would rather have installed galliumos but I needed the machine working.

**Comment by reynhout** [comment]
@rongreg Your command line is not quite right: `-a i386` is the wrong architecture for your device. You can just leave that option off, and chrx will default to the correct `-a amd64`.

However, I'm not sure if that would cause the error you saw.

The core image download is succeeding for me. I will update when I'm able to do a full and proper test.

Thank you for the report!

**Comment by reynhout** [comment]
I've tested with and without the `-a` option. Both work fine, so you must have just hit a transient/network issue. I'll close this ticket, but please let us know if you see any other issues.

**Comment by rongreg** [comment]
OK. Thanks for your assistance.

On Dec 12, 2018 4:54 PM, "reynhout" <notifications@github.com> wrote:

I've tested with and without the -a option. Both work fine, so you must
have just hit a transient/network issue. I'll close this ticket, but please
let us know if you see any other issues.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/reynhout/chrx/issues/70#issuecomment-446789366>, or mute
the thread
