### ISSUE TITLE
fedora boot to grub cursor

### ISSUE THREAD

**Issue by kgolap** [reynhout/chrx#71]
Trying to install fedora...the process goes through but at boot time it goes to a grub cursor.

Try to repair grub but when using (after doing the chroot shenanigan to /dev/sda7)
grub2-install /dev/sda
It fails complaining that could not find partition label with bios label or something like that.

**Comment by jedigo** [comment]
Hi all, sorry for the long delay. This should be fixed in #84 

Please feel free to tag me if there are any issues with Fedora.

**Comment by reynhout** [comment]
Fixes in #84 merged and deployed to chrx.org. Thanks @jedigo!
