### ISSUE TITLE
FYI: Disabling shell script usage on noexec mounts

### ISSUE THREAD

**Issue by DennisLfromGA** [reynhout/chrx#76]
Hopefully, you're aware of this but if not just a heads up -

- [[PSA] disabling shell script usage on noexec mounts redux](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/X3SSyk6mFDY)

Not sure exactly what effect this might have on your scripts but thought I'd mention it.

-**DennisLfromGA**

**Comment by reynhout** [comment]
@DennisLfromGA Thank you for the heads-up! I am not certain of the effects yet either, but will need to do some testing.

It looks like [M75 is scheduled for release in June 2019](https://www.chromium.org/developers/calendar), which isn't as far away as it sounds... :)

**Comment by reynhout** [comment]
A new version of chrx, with ChromeOS R82-compatible installation instructions, is released. Thanks for the early warning!

**Comment by DennisLfromGA** [comment]
Nice fix solution.
