### ISSUE TITLE
fedora fails to install

### ISSUE THREAD

**Issue by mjonsson1986** [reynhout/chrx#77]
fedora 29,28,27,26 fails to install. the scripts try to download som form of tar file, but fail. and the tar command fail. 
to reproduce try to install e.g fedora 28 with minimal ui the minimal.

**Comment by AshtonGamerYT** [comment]
Currently, the server that it is trying to connect has been moved to another website, and the download on the download chrx is trying to get is down. I am trying to get 27, 25, 24 tar currently working on my version of the script, but I can only do one at a time. After looking through the website, I found out Fedora 28+ don't have the tar install files, so for now the max version we are gonna get is 27 I think. With my script download the correct files, it is still having problems installing things for the chromebook, so I think I may have to do just a normal install.

**Comment by AshtonGamerYT** [comment]
EDIT TO ABOVE: I think I found some docker files (tar) for Fedora 28 and above, might try to test these.

**Comment by AshtonGamerYT** [comment]
#78 
^Pull Request (you need to change the chrx go script to my github if you want to make it work before the pull request gets accepted) 
MORE EDITS: Having a lot of troubles with locale script errors. Still should work.

**Comment by r3vela710n** [comment]
Fedora link still not working.. Any word on when you expect the updated repo link will make it into the chrx script on https://chrx.org? Will 3.0 be supported? I wish I had the skills to figure this out myself, however i'm just starting out in the wonderful world of chromeboxes and linux

**Comment by jedigo** [comment]
Hi all, sorry for the long delay. This should be fixed in #84 

Please feel free to tag me if there are any issues with Fedora.

**Comment by reynhout** [comment]
Fixes in #84 merged and deployed to chrx.org. Thanks @jedigo!
