### ISSUE TITLE
All Fedora Versions have trouble install chrx "drivers"

### ISSUE THREAD

**Issue by AshtonGamerYT** [reynhout/chrx#79]
In my Pull Request #78  I changed to Fedora repo to a working one for the Fedora 27 Docker tar. But, we have some more problems. 
1. Locale scripts won't work with errors spitting out through out the installer.
2. Chrx Configurations/Drivers for things like WiFi, etc... don't work and say file not found at the very end of the installer.

**Comment by jedigo** [comment]
Hi all, sorry for the long delay. This should be fixed in #84 

Please feel free to tag me if there are any issues with Fedora.

**Comment by reynhout** [comment]
Fixes in #84 merged and deployed to chrx.org. Thanks @jedigo!
