### ISSUE TITLE
are it possible to install fedora yet?

### ISSUE THREAD

**Issue by mjonsson1986** [reynhout/chrx#80]
as topic. are it possible to install fedora yet? or are it still broken

**Comment by choephel** [comment]
Nope. I still get the same output no matter which version I try to install.

`Fetching Fedora core image file...
HTTP GET https://download.fedoraproject.org/pub/fedora/linux/releases/27/Docker/x86_64/images/Fedora-Docker-Base-27-1.6.x86_64.tar.xz
##O=#   #                                                                                                                                    
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
fatal: unable to download and extract core image file.`

**Comment by mjonsson1986** [comment]
But try to create a bootable usb stick and boot the chromebook and install to the partition Skickades från E-post för Windows 10 Från: choephelSkickat: den 12 juli 2019 05:27Till: reynhout/chrxKopia: mjonsson1986; AuthorÄmne: Re: [reynhout/chrx] are it possible to install fedora yet? (#80) Nope. I still get the same output no matter which version I try to install.Fetching Fedora core image file... HTTP GET https://download.fedoraproject.org/pub/fedora/linux/releases/27/Docker/x86_64/images/Fedora-Docker-Base-27-1.6.x86_64.tar.xz ##O=# # xz: (stdin): File format not recognized tar: Child returned status 1 tar: Error is not recoverable: exiting now fatal: unable to download and extract core image file.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jedigo** [comment]
Hi all, sorry for the long delay. This should be fixed in #84 

Please feel free to tag me if there are any issues with Fedora.

**Comment by reynhout** [comment]
Fixes in #84 merged and deployed to chrx.org. Thanks @jedigo!
