### ISSUE TITLE
Unable to boot GalliumOS (hang on booting on disk)

### ISSUE THREAD

**Issue by aidylewis** [reynhout/chrx#82]
Model:       HP Chromebook 11 G5/11-vxxx
    Released:    2016
    CPU Family:  Intel Braswell
    Prognosis:   success likely, ONLY IF FIRMWARE HAS BEEN UPDATED!

I've updated the firmware for my CPU ```Install/Update RW_LEGACY Firmware ```

However, when I  ```ctrl-l```, I hang on booting on disk.

**Comment by aidylewis** [comment]
In fact, I didn't update, I just rebooted. I suppose I choose option 3. 

```
**      1) Install/Update RW_LEGACY Firmware 
**      2) Install/Update BOOT_STUB Firmware 
** [WP] 3) Install/Update Full ROM Firmware 
** [WP] 4) Set Boot Options (GBB flags) 
** [WP] 5) Set Hardware ID (HWID) 
** [WP] 6) Remove ChromeOS Bitmaps 
** [WP] 7) Restore ChromeOS Bitmaps 
**      8) Restore Stock BOOT_STUB 
**      9) Restore Stock Firmware (full) 
```

**Comment by reynhout** [comment]
@aidylewis Were you able to get past this issue?

Thanks, and sorry for the late reply!

**Comment by aidylewis** [comment]
HI @reynhout 

No unfortunately not, so I bought a second had Thinkpad and put LXLE on,
