### ISSUE TITLE
completely screwed up..

### ISSUE THREAD

**Issue by jonasthenoob** [reynhout/chrx#85]
okay so i legit have like 20mb space on chrome os but thats not a problem to me the problem is that i was just messing about with fdisk and like i accidently deleted the partition with chrx in it and i moved it to microsoft basic data.
Please Help Me.
![image](https://user-images.githubusercontent.com/57160032/67819111-bc7a6400-faab-11e9-856d-48864140f146.png)
the partition i deleted was /dev/mmcblk0p7 and now i can't even reinstall like chrx with new desktops like lxde and fedora it just says fatal error cannot find /dev/mmcblk0p7, something like that.

**Comment by jonasthenoob** [comment]
like how do i revert this progress without the recovery utility.

**Comment by reynhout** [comment]
If you remember the exact layout, you can _probably_ force a partition table rewrite and get things working again. p7 probably started at `12804096`, and p8 was probably 1MB in size. The end isn't usually critical though, if you can force p7 to start at p8's current start sector, you can probably boot (might require fixing the partition UUID though).

First, I'd try resetting the partition type, and mounting p8. You might be able to read the partition directly. Then back up the data, Recover ChromeOS, reinstall Linux...

BTW, your method for resizing ChromeOS partitions would not have worked. The ChromeOS `cgpt` tool works, but it's a bit awkward to use. Backing up data, Recovering ChromeOS, and reinstalling is by far the safest method -- and usually also the fastest.

**Comment by jonasthenoob** [comment]
sorry i am a pretty big noob at chromeos cn to tell me the commands to force p7 to start at p8 current  start sector.
