### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by jonasthenoob** [reynhout/chrx#86]
sorry i am a pretty big noob at chromeos can you tell me the commands to force p7 to start at p8 current start sector.

**Comment by reynhout** [comment]
I can't safely provide much detail, without access to the device.

I will assume that you do not care about recovering any ChromeOS data from the disk. (If that's wrong, you're almost surely out of luck, but any hope you might have runs through `cgpt`. ChromeOS data should be synced to Google though.).

For GalliumOS data, I would avoid messing around with the partition tables any more than you already have. Just try to mount p8, in ChromeOS or booted from the GalliumOS install image. You might be able to read data directly.

If that doesn't work, your partition table is damaged. You might be able to rewrite it to its original state (p7 of the appropriate size, p8 after it) and have things work. Or you might make things worse by trying. If you're feeling brave or desperate, `fdisk` is the tool to use. Then try to mount the new p7, as above.

If you can get the partition mounted, copy the data off to a USB drive, then Recover and reinstall.

If you can live without the data, the easy path is to just Recover and reinstall. Be sure to make regular backups in the future.

Good luck!
