### ISSUE TITLE
Installation process appears to complete successfully but Ctrl + L doesn't do anything

### ISSUE THREAD

**Issue by mrjohnc** [reynhout/chrx#89]
I'm trying to install on a Lenovo Yoga Chromebook C630, I have gone through the installation process (I've tried Gallium, Ubuntu and Fedora) and they all appear to complete successfully (giving me the message about Ctrl+L to boot into Linux etc). However when I try to boot into Linux the computer appears to freeze because it doesn't do anything and Ctrl + D stops working. If I restart I can Ctrl + D to get into Chrome OS but that's it. 

Is there any way to see what the issue might be? 

Thanks very much

**Comment by jonasthenoob** [comment]
have you done the firmware update?
using me chomebox's script

________________________________

**Comment by mrjohnc** [comment]
Ah, OK I worked it out, yes the problem was not having firmware updated correctly. One thing that would have been helpful from the chrx.org instructions is saying which firmware is needed to make installation successful. This will help people understand which are the least invasive options they can chose to install Linux, e.g the Legacy Firmware

**Comment by reynhout** [comment]
@mrjohnc Good point. Those docs were written when there was only one firmware option available. Updated to specify RW_LEGACY, which is the only option that will work with chrx.

**Comment by jonasthenoob** [comment]
Glad to hear that your problem is fixed and yes i agree maybe you should update the chrx.org website and be more specific.
________________________________

**Comment by mrjohnc** [comment]
Thanks very much @reynhout for improving the documentation. One additional piece of documentation that may be helpful is linking to the hardware compatibility list for Gallium (I went through the whole installation procedure not realising my speakers and microphone wouldn't work) https://wiki.galliumos.org/Hardware_Compatibility , maybe in the notes section of the operating systems?

**Comment by reynhout** [comment]
@mrjohnc Also a good suggestion, thanks. The compatibility list is linked immediately above the operating systems table, but it could use some more emphasis.

The presentation might be a bit tricky -- the list is written for GalliumOS, but it generally reflects the best-case scenario for _all_ distros, and of course the other distros do not have Chromebook compat lists to compare against.

I'll take a look and see how to fit it in. Thanks again!

And thanks also to @jonasthenoob for IDing the initial issue.

**Comment by mrjohnc** [comment]
@reynhout thanks very much :)

**Comment by jonasthenoob** [comment]
Sorry i'm late but my pleasure. @reynhout
