### ISSUE TITLE
Minimal / Core Install for Lubuntu

### ISSUE THREAD

**Issue by fortes** [reynhout/chrx#9]
Thanks for chrx, this is great. I'm wondering if it's possible to install only the Lubuntu core modules, without Chrome / Abiword / etc / etc.

Thanks!

**Comment by reynhout** [comment]
I don't think so.

Lubuntu only has a single distribution (`lubuntu-desktop`) as far as I know, which includes all the desktop stuff you mentioned.

You might be able to get a smaller Lubuntu-ish system by selecting `ubuntu-mininal` or `ubuntu-standard` and then adding the lxde packages? Maybe just `lxde`?

So, something like this, perhaps:

    curl -Os https://chrx.org/go && sh go -d ubuntu -e minimal -p lxde

**Comment by fortes** [comment]
Understood, thanks!
