### ISSUE TITLE
Fix for nonexec.

### ISSUE THREAD

**Issue by HUSKI3** [reynhout/chrx#91]
Hello,
While reinstalling GalliumOS I encountered the new (or not so new for dev build) problem. I was able to get past it before by putting the "go" script into a different location where I could execute it. I recommend updating the README with this.
`cd ; curl -Os https://chrx.org/go && sudo install -Dt /usr/local/bin -m 755 go && go`
This may have security issues, but im not an expert with how ChromeOS works.
But the installation is successful and works without any problems on Asus C423N.
Hopefully this helps.

**Comment by reynhout** [comment]
Hi @HUSKI3 

The new command line I'm leaning toward is this:

```
curl https://chrx.org/ | sudo tar xzfC - /usr/local && chrx
```

This should work today (and is required for the dev channel). I think the noexec change will come in M82, which is scheduled for initial public release in a few weeks.

**Comment by HUSKI3** [comment]
Yep, that does the job.
Thank you!

**Comment by reynhout** [comment]
A new version of chrx, with ChromeOS M82-compatible installation instructions, is released.
