### ISSUE TITLE
CloudReady support

### ISSUE THREAD

**Issue by DanielHerr** [reynhout/chrx#93]
Attempting to run chrx in CloudReady on a non-Chrome device results in failure after being unable to find legacy boot mode.

**Comment by reynhout** [comment]
This seems reasonable to me..! What function would chrx perform in CloudReady on a non-ChromeOS device? :)

**Comment by DanielHerr** [comment]
It would perform the same function of repartitioning to dual boot Linux as for Chrome OS, since CloudReady has a similarly peculiar partitioning scheme.

**Comment by DanielHerr** [comment]
I had wrongly assumed that CloudReady, like Chrome OS would refuse to boot or malfunction as a result of shrinking the state partition and adding a new partition in its space. However, despite apparently discontinuing official support for dual booting, CloudReady seems to work fine after manually repartitioning. Given the ease of shrinking the single largest partition and adding a new one using GUI tools such as GParted or Ubuntu's installer, I don't think it is necessary to add CloudReady support to chrx.
