### ISSUE TITLE
Chrx Install script installs Google Chrome automatically without an opt-out option

### ISSUE THREAD

**Issue by saltedcoffeeuwu** [reynhout/chrx#95]
I love chrx so much and actively use it's Ubuntu install, however the install script adds the Google Chrome software repository and automatically installs Google Chrome.
I would really appreciate if the dev team would consider adding Google Chrome as an extra package like Minecraft instead of automatically installing it, or if that's not possible/desired that an option, say `-p chrome-` or just `-o` for opt-out be added. I use Ubuntu because I value privacy and Google Chrome and Google in general really breaks that with their analytic tracking.
Thanks for considering!

**Comment by reynhout** [comment]
@saltedcoffeeuwu Thanks, that's a good idea. I don't use Ubuntu and I had forgotten that we were installing Google Chrome by default. Fixed now in chrx-3.0.1.

It is still possible to install Chrome from the chrx command line, using `-p chrome`.

**Comment by saltedcoffeeuwu** [comment]
Thanks so much!
