### ISSUE TITLE
Everything seeming to work but GalliumOS not booting....

### ISSUE THREAD

**Issue by ElderFrost** [reynhout/chrx#96]
Hey,
I followed all the instructions, I have the firmware installed, the drive partitioned, and Gallium OS downloaded, and I'm pretty sure it all worked correctly. When I reboot the chromebook it shows the white screen that says OS verification is off, and when I hit ctrl+L it goes to the seaBOIS boot page, but it doesn't go past that, it just says booting and doesn't ever actually boot up Gallium, even when waiting for 20+ minutes. I can't even exit the page without rebooting the computer again. I can still access ChromeOS. 
Does anyone else have this problem or know how to fix it? I'm on a ASUS Chromebook Flip C302C if that helps.

**Comment by reynhout** [comment]
Sorry for not seeing this sooner ... you've probably already resolved one way or another, but my only suggestion would have been: Install definitely failed, you should try again. I don't have a CAVE to test on, but everything works on similar machines.
