### ISSUE TITLE
Instructions for using chrx partition with Crouton?

### ISSUE THREAD

**Issue by satmandu** [reynhout/chrx#99]
Chrx worked great to setup a separate boot partition on my pixel slate, but I want to be able to use apps from the Linux install from when I am booted into ChromeOS.

Could there be instructions or an option on how to direct crouton to just chroot to the partition that chrx creates?

I've just been mounting /dev/mmcblk0p7 to /mnt/empty when I have needed to get or put files, but that might not be the safest way.

Happy to help beta test too.

**Comment by reynhout** [comment]
@satmandu I think mounting is your only option. You can do something like this to focus on your user data:

```
sudo mount /dev/mmcblk0p7 /mnt/chrx
ln -s /mnt/chrx/home/USERNAME $HOME/chrx
```

(I'm not sure what will work in the Crouton env, but that's the idea)

Crouton runs the ChromeOS kernel, so it cannot chroot into the OS partition installed by chrx.
